#Juntada -- plantilla del repo (proyectos/ingenieria/minecraft-amigos/servidor). Se copia al server.
motd=§6La Juntada §7- Fabric 1.21.4
level-name=juntada
gamemode=survival
difficulty=normal
max-players=8
online-mode=false
enforce-secure-profile=false
allow-flight=true
spawn-protection=0
view-distance=10
simulation-distance=8
sync-chunk-writes=false
pvp=true
server-port=25565
enable-command-block=false
